### ISSUE TITLE
After reattaching the instances moves

### ISSUE THREAD

**Issue by alexcamlo** [renancamm/figma-reattache-instance#14]
As you can see in the images, after the plugin reattaches the instance, this moves down.

![before](https://user-images.githubusercontent.com/121455/78757472-d97d6200-797c-11ea-833b-b646939cb3fd.png)

![after](https://user-images.githubusercontent.com/121455/78757487-dda97f80-797c-11ea-8e92-f3c8eb1e5602.png)

**Comment by alexcamlo** [comment]
It seems an issue with Figma because it is showing a Y value that is not the correct one.

**Comment by renancamm** [comment]
maybe we need to update the props list
https://github.com/renancamm/figma-reattache-instance/blob/05f4a6c64b4347c17de642b8dd720fba5ba5bd4d/code.ts#L249

we never made any change after the new autolayout

**Comment by alexcamlo** [comment]
I think is an issue with Figma. The incorrect Y value is showing before even using the plugin.
